#!/bin/bash

# This script file resets the local OpenBazaar instance so that tests can be re-run.

docker-compose down
sudo rm -rf test/obdata/*
docker run --rm -v $(pwd)/test/obdata:/var/lib/openbazaar p2pvps/ob-server:v0.12.2 init -d /var/lib/openbazaar
sudo cp test/setup/config test/obdata/
docker-compose up -d
