#!/bin/bash

# This is a setup script to install OpenBazaar on Travis CI.
pwd

# Install dependencies.
sudo apt-get install -y build-essential git

# Install go
wget https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz
sudo tar -zxvf  go1.9.1.linux-amd64.tar.gz -C /usr/local/

# Setup environment variables
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin

# Get OB source code
go get github.com/OpenBazaar/openbazaar-go

# Initialize OB
cd $GOPATH/src/github.com/OpenBazaar/openbazaar-go
pwd
echo "Initializing OB"
go run openbazaard.go init

pwd
cd
pwd
cd .openbazaar2.0
pwd
cp /home/travis/build/P2PVPS/openbazaar-node/test/setup/config .
ls
